### ISSUE TITLE
[DEV] Setup API/GIT/Personal DB/DEV DB

### ISSUE THREAD

**Issue by eunbeek** [YourMoneyMyMoney/ymmm_core#2]
- project setup (eunbee, jiung)
- git setup (eunbee, jiung)
- personal db setup (eunbee, jiung)
- dev db setup (eunbee)

**Comment by eunbeek** [comment]
- [x] project setup 
- [x] git setup
- [x] personal db setup : docker + postgresql 16(15 버전 다운그레이드 필요)
- [x] dev db setup : aws 설치 완료 (현재 구동 중, 3.129.59.112:5432)

**Comment by eunbeek** [comment]
@FullStackJiung 
해당 설치 완료 여부 알려주세요

**Comment by FullStackJiung** [comment]
@eunbeek aws 제외하고 완료했습니다
